required_packages:
  - tclsh
  - pkg-config
  - libssl-dev
  - build-essential
  - make
  - cmake
  - tcl
  - openssl
  - zlib1g-dev
  - gcc
  - perl
  - net-tools
  - git
  - zip
  - unzip

sls_conf: |
  srt {
    worker_threads 1;
    worker_connections 200;
    http_port 8181;
    cors_header *;
    log_file /dev/stdout;

    server {
        listen 8282;
        latency 2000;
        domain_player play;
        domain_publisher live;
        default_sid play/stream/PUT YOUR KEY-GIVE A NAME HERE;
        backlog 10;
        idle_streams_timeout 5;

        app {
            app_publisher stream;
            app_player stream;
        }
    }
  }

sls_repo: https://gitlab.com/mattwb65/srt-live-server.git
srt_repo: https://github.com/Haivision/srt.git