- name: Clone and build repositories
  hosts: all
  become: true
  tasks:
    - name: Clone repo srt-live-server
      ansible.builtin.git:
        repo: "{{ sls_repo }}"
        dest: /root/srt-live-server
        version: 0fd87d0694c468bef4c1f2f0c9fe7c07ee27ec00
        update: false

    - name: Clone repo srt
      ansible.builtin.git:
        repo: "{{ srt_repo }}"
        dest: /root/srt
        version: 899348d8318eb9a3c5a5b6ec43c4a1114288773a
        update: false

    - name: Build SRT
      ansible.builtin.shell:
        cmd: |
          ./configure && make -j8 && make install
          touch /root/srt_built.marker
        chdir: /root/srt
        creates: /root/srt_built.marker

    - name: Edit sls file
      ansible.builtin.lineinfile:
        path: /root/srt-live-server/slscore/common.cpp
        insertafter: '^#include <vector>'
        line: '#include <time.h>'

    - name: Build srt-live-server
      ansible.builtin.shell:
        cmd: |
          make -j8
          touch /root/sls_built.marker
        chdir: /root/srt-live-server
        creates: /root/sls_built.marker

    - name: Run ldconfig for SRT Live Server libraries
      ansible.builtin.command: ldconfig
      changed_when: false
