- name: clone and build repos
  hosts: all
  become: true
  tasks:
    - name: Clone repo srt-live-server
      ansible.builtin.git:
        repo: "{{ sls_repo }}"
        dest: /root/srt-live-server
        update: no

    - name: Clone repo srt
      ansible.builtin.git:
        repo: "{{ srt_repo }}"
        dest: /root/srt
        update: no

    - name: Build SRT
      ansible.builtin.shell:
        cmd: |
          ./configure && make -j8 && make install
          touch /root/srt_built.marker
        chdir: /root/srt
        creates: /root/srt_built.marker

    - name: Edit sls file
      ansible.builtin.lineinfile:
        path: /root/srt-live-server/slscore/common.cpp
        insertafter : '^#include <vector>'
        line: '#include <time.h>'

    - name: Build srt-live-server
      ansible.builtin.shell:
        cmd: |
          make -j8
          touch /root/sls_built.marker
        chdir: /root/srt-live-server
        creates: /root/sls_built.marker

    - name: Run ldconfig for SRT Live Server libraries
      ansible.builtin.shell:
        cmd: ldconfig
        chdir: /root/srt-live-server/bin/
