---
- name: Create systemd service
  hosts: all
  become: true
  tasks:
    - name: Create bash start script
      ansible.builtin.copy:
        dest: /root/sls.sh
        content: |
          #!/bin/bash
          cd /root/srt-live-server/bin/
          ./sls -c ../sls.conf
        mode: '0755'

    - name: Create systemd file
      ansible.builtin.copy:
        dest: /etc/systemd/system/sls.service
        content: |
          [Unit]
          Description=srt server
          After=network.target

          [Service]
          ExecStart=/root/sls.sh
          Restart=always
          RestartSec=5s

          [Install]
          WantedBy=multi-user.target
        mode: '0640'

    - name: Start service
      ansible.builtin.systemd_service:
        name: sls.service
        state: started
        daemon_reload: true
        enabled: true