---
- name: Install necessary packages
  hosts: all
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: "{{ required_packages }}"
        state: present
        update_cache: true
