---
- name: Setup congif files
  hosts: all
  become: true
  tasks:
  - name: Edit main config files
    ansible.builtin.copy:
      dest: /root/srt-live-server/sls.conf
      content: '{{ sls_conf }}'
      backup: yes
      force: no